// Package growthbookapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package growthbookapi

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for FeatureValueType.
const (
	Boolean FeatureValueType = "boolean"
	Json    FeatureValueType = "json"
	Number  FeatureValueType = "number"
	String  FeatureValueType = "string"
)

// Defines values for FeatureExperimentRefRuleType.
const (
	ExperimentRef FeatureExperimentRefRuleType = "experiment-ref"
)

// Defines values for FeatureExperimentRuleType.
const (
	Experiment FeatureExperimentRuleType = "experiment"
)

// Defines values for FeatureForceRuleSavedGroupTargetingMatchType.
const (
	FeatureForceRuleSavedGroupTargetingMatchTypeAll  FeatureForceRuleSavedGroupTargetingMatchType = "all"
	FeatureForceRuleSavedGroupTargetingMatchTypeAny  FeatureForceRuleSavedGroupTargetingMatchType = "any"
	FeatureForceRuleSavedGroupTargetingMatchTypeNone FeatureForceRuleSavedGroupTargetingMatchType = "none"
)

// Defines values for FeatureForceRuleType.
const (
	Force FeatureForceRuleType = "force"
)

// Defines values for FeatureRolloutRuleSavedGroupTargetingMatchType.
const (
	FeatureRolloutRuleSavedGroupTargetingMatchTypeAll  FeatureRolloutRuleSavedGroupTargetingMatchType = "all"
	FeatureRolloutRuleSavedGroupTargetingMatchTypeAny  FeatureRolloutRuleSavedGroupTargetingMatchType = "any"
	FeatureRolloutRuleSavedGroupTargetingMatchTypeNone FeatureRolloutRuleSavedGroupTargetingMatchType = "none"
)

// Defines values for FeatureRolloutRuleType.
const (
	Rollout FeatureRolloutRuleType = "rollout"
)

// Defines values for FeatureSafeRolloutRuleSavedGroupTargetingMatchType.
const (
	All  FeatureSafeRolloutRuleSavedGroupTargetingMatchType = "all"
	Any  FeatureSafeRolloutRuleSavedGroupTargetingMatchType = "any"
	None FeatureSafeRolloutRuleSavedGroupTargetingMatchType = "none"
)

// Defines values for FeatureSafeRolloutRuleStatus.
const (
	Released   FeatureSafeRolloutRuleStatus = "released"
	RolledBack FeatureSafeRolloutRuleStatus = "rolled-back"
	Running    FeatureSafeRolloutRuleStatus = "running"
	Stopped    FeatureSafeRolloutRuleStatus = "stopped"
)

// Defines values for FeatureSafeRolloutRuleType.
const (
	SafeRollout FeatureSafeRolloutRuleType = "safe-rollout"
)

// Feature defines model for Feature.
type Feature struct {
	Archived     bool                          `json:"archived"`
	CustomFields *map[string]interface{}       `json:"customFields,omitempty"`
	DateCreated  time.Time                     `json:"dateCreated"`
	DateUpdated  time.Time                     `json:"dateUpdated"`
	DefaultValue string                        `json:"defaultValue"`
	Description  string                        `json:"description"`
	Environments map[string]FeatureEnvironment `json:"environments"`
	Id           string                        `json:"id"`
	Owner        string                        `json:"owner"`

	// Prerequisites Feature IDs. Each feature must evaluate to `true`
	Prerequisites *[]string `json:"prerequisites,omitempty"`
	Project       string    `json:"project"`
	Revision      struct {
		Comment     string    `json:"comment"`
		Date        time.Time `json:"date"`
		PublishedBy string    `json:"publishedBy"`
		Version     int       `json:"version"`
	} `json:"revision"`
	Tags      []string         `json:"tags"`
	ValueType FeatureValueType `json:"valueType"`
}

// FeatureValueType defines model for Feature.ValueType.
type FeatureValueType string

// FeatureEnvironment defines model for FeatureEnvironment.
type FeatureEnvironment struct {
	DefaultValue string `json:"defaultValue"`

	// Definition A JSON stringified [FeatureDefinition](#tag/FeatureDefinition_model)
	Definition *string `json:"definition,omitempty"`
	Draft      *struct {
		DefaultValue string `json:"defaultValue"`

		// Definition A JSON stringified [FeatureDefinition](#tag/FeatureDefinition_model)
		Definition *string       `json:"definition,omitempty"`
		Enabled    bool          `json:"enabled"`
		Rules      []FeatureRule `json:"rules"`
	} `json:"draft,omitempty"`
	Enabled bool          `json:"enabled"`
	Rules   []FeatureRule `json:"rules"`
}

// FeatureExperimentRefRule defines model for FeatureExperimentRefRule.
type FeatureExperimentRefRule struct {
	Condition     *string                      `json:"condition,omitempty"`
	Description   string                       `json:"description"`
	Enabled       bool                         `json:"enabled"`
	ExperimentId  string                       `json:"experimentId"`
	Id            string                       `json:"id"`
	ScheduleRules *[]ScheduleRule              `json:"scheduleRules,omitempty"`
	Type          FeatureExperimentRefRuleType `json:"type"`
	Variations    []struct {
		Value       string `json:"value"`
		VariationId string `json:"variationId"`
	} `json:"variations"`
}

// FeatureExperimentRefRuleType defines model for FeatureExperimentRefRule.Type.
type FeatureExperimentRefRuleType string

// FeatureExperimentRule defines model for FeatureExperimentRule.
type FeatureExperimentRule struct {
	BucketVersion          *float32 `json:"bucketVersion,omitempty"`
	Condition              string   `json:"condition"`
	Coverage               *float32 `json:"coverage,omitempty"`
	Description            string   `json:"description"`
	DisableStickyBucketing *bool    `json:"disableStickyBucketing,omitempty"`
	Enabled                bool     `json:"enabled"`
	FallbackAttribute      *string  `json:"fallbackAttribute,omitempty"`
	HashAttribute          *string  `json:"hashAttribute,omitempty"`
	Id                     string   `json:"id"`
	MinBucketVersion       *float32 `json:"minBucketVersion,omitempty"`
	Namespace              *struct {
		Enabled bool      `json:"enabled"`
		Name    string    `json:"name"`
		Range   []float32 `json:"range"`
	} `json:"namespace,omitempty"`
	ScheduleRules *[]ScheduleRule           `json:"scheduleRules,omitempty"`
	TrackingKey   *string                   `json:"trackingKey,omitempty"`
	Type          FeatureExperimentRuleType `json:"type"`
	Value         *[]struct {
		Name   *string `json:"name,omitempty"`
		Value  string  `json:"value"`
		Weight float32 `json:"weight"`
	} `json:"value,omitempty"`
}

// FeatureExperimentRuleType defines model for FeatureExperimentRule.Type.
type FeatureExperimentRuleType string

// FeatureForceRule defines model for FeatureForceRule.
type FeatureForceRule struct {
	Condition     string `json:"condition"`
	Description   string `json:"description"`
	Enabled       bool   `json:"enabled"`
	Id            string `json:"id"`
	Prerequisites *[]struct {
		Condition string `json:"condition"`

		// Id Feature ID
		Id string `json:"id"`
	} `json:"prerequisites,omitempty"`
	SavedGroupTargeting *[]struct {
		MatchType   FeatureForceRuleSavedGroupTargetingMatchType `json:"matchType"`
		SavedGroups []string                                     `json:"savedGroups"`
	} `json:"savedGroupTargeting,omitempty"`
	ScheduleRules *[]ScheduleRule      `json:"scheduleRules,omitempty"`
	Type          FeatureForceRuleType `json:"type"`
	Value         string               `json:"value"`
}

// FeatureForceRuleSavedGroupTargetingMatchType defines model for FeatureForceRule.SavedGroupTargeting.MatchType.
type FeatureForceRuleSavedGroupTargetingMatchType string

// FeatureForceRuleType defines model for FeatureForceRule.Type.
type FeatureForceRuleType string

// FeatureRolloutRule defines model for FeatureRolloutRule.
type FeatureRolloutRule struct {
	Condition           string  `json:"condition"`
	Coverage            float32 `json:"coverage"`
	Description         string  `json:"description"`
	Enabled             bool    `json:"enabled"`
	HashAttribute       string  `json:"hashAttribute"`
	Id                  string  `json:"id"`
	SavedGroupTargeting *[]struct {
		MatchType   FeatureRolloutRuleSavedGroupTargetingMatchType `json:"matchType"`
		SavedGroups []string                                       `json:"savedGroups"`
	} `json:"savedGroupTargeting,omitempty"`
	ScheduleRules *[]ScheduleRule        `json:"scheduleRules,omitempty"`
	Type          FeatureRolloutRuleType `json:"type"`
	Value         string                 `json:"value"`
}

// FeatureRolloutRuleSavedGroupTargetingMatchType defines model for FeatureRolloutRule.SavedGroupTargeting.MatchType.
type FeatureRolloutRuleSavedGroupTargetingMatchType string

// FeatureRolloutRuleType defines model for FeatureRolloutRule.Type.
type FeatureRolloutRuleType string

// FeatureRule defines model for FeatureRule.
type FeatureRule struct {
	union json.RawMessage
}

// FeatureSafeRolloutRule defines model for FeatureSafeRolloutRule.
type FeatureSafeRolloutRule struct {
	Condition     string  `json:"condition"`
	ControlValue  string  `json:"controlValue"`
	Enabled       bool    `json:"enabled"`
	HashAttribute *string `json:"hashAttribute,omitempty"`
	Id            string  `json:"id"`
	Prerequisites *[]struct {
		Condition string `json:"condition"`

		// Id Feature ID
		Id string `json:"id"`
	} `json:"prerequisites,omitempty"`
	SafeRolloutId       *string `json:"safeRolloutId,omitempty"`
	SavedGroupTargeting *[]struct {
		MatchType   FeatureSafeRolloutRuleSavedGroupTargetingMatchType `json:"matchType"`
		SavedGroups []string                                           `json:"savedGroups"`
	} `json:"savedGroupTargeting,omitempty"`
	ScheduleRules  *[]ScheduleRule               `json:"scheduleRules,omitempty"`
	Seed           *string                       `json:"seed,omitempty"`
	Status         *FeatureSafeRolloutRuleStatus `json:"status,omitempty"`
	TrackingKey    *string                       `json:"trackingKey,omitempty"`
	Type           FeatureSafeRolloutRuleType    `json:"type"`
	VariationValue string                        `json:"variationValue"`
}

// FeatureSafeRolloutRuleSavedGroupTargetingMatchType defines model for FeatureSafeRolloutRule.SavedGroupTargeting.MatchType.
type FeatureSafeRolloutRuleSavedGroupTargetingMatchType string

// FeatureSafeRolloutRuleStatus defines model for FeatureSafeRolloutRule.Status.
type FeatureSafeRolloutRuleStatus string

// FeatureSafeRolloutRuleType defines model for FeatureSafeRolloutRule.Type.
type FeatureSafeRolloutRuleType string

// PaginationFields defines model for PaginationFields.
type PaginationFields struct {
	Count      int  `json:"count"`
	HasMore    bool `json:"hasMore"`
	Limit      int  `json:"limit"`
	NextOffset *int `json:"nextOffset"`
	Offset     int  `json:"offset"`
	Total      int  `json:"total"`
}

// ScheduleRule An array of schedule rules to turn on/off a feature rule at specific times. The array must contain exactly 2 elements (start rule and end rule). The first element is the start rule.
type ScheduleRule struct {
	// Enabled Whether the rule should be enabled or disabled at the specified timestamp.
	Enabled bool `json:"enabled"`

	// Timestamp ISO timestamp when the rule should activate.
	Timestamp *time.Time `json:"timestamp"`
}

// ClientKey defines model for clientKey.
type ClientKey = string

// Id defines model for id.
type Id = string

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = int

// ProjectId defines model for projectId.
type ProjectId = string

// VisualChangeId defines model for visualChangeId.
type VisualChangeId = string

// ListFeaturesParams defines parameters for ListFeatures.
type ListFeaturesParams struct {
	// Limit The number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset How many items to skip (use in conjunction with limit for pagination)
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// ProjectId Filter by project id
	ProjectId *ProjectId `form:"projectId,omitempty" json:"projectId,omitempty"`

	// ClientKey Filter by a SDK connection's client key
	ClientKey *ClientKey `form:"clientKey,omitempty" json:"clientKey,omitempty"`
}

// AsFeatureForceRule returns the union data inside the FeatureRule as a FeatureForceRule
func (t FeatureRule) AsFeatureForceRule() (FeatureForceRule, error) {
	var body FeatureForceRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureForceRule overwrites any union data inside the FeatureRule as the provided FeatureForceRule
func (t *FeatureRule) FromFeatureForceRule(v FeatureForceRule) error {
	v.Type = "force"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureForceRule performs a merge with any union data inside the FeatureRule, using the provided FeatureForceRule
func (t *FeatureRule) MergeFeatureForceRule(v FeatureForceRule) error {
	v.Type = "force"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureRolloutRule returns the union data inside the FeatureRule as a FeatureRolloutRule
func (t FeatureRule) AsFeatureRolloutRule() (FeatureRolloutRule, error) {
	var body FeatureRolloutRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureRolloutRule overwrites any union data inside the FeatureRule as the provided FeatureRolloutRule
func (t *FeatureRule) FromFeatureRolloutRule(v FeatureRolloutRule) error {
	v.Type = "rollout"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureRolloutRule performs a merge with any union data inside the FeatureRule, using the provided FeatureRolloutRule
func (t *FeatureRule) MergeFeatureRolloutRule(v FeatureRolloutRule) error {
	v.Type = "rollout"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureExperimentRule returns the union data inside the FeatureRule as a FeatureExperimentRule
func (t FeatureRule) AsFeatureExperimentRule() (FeatureExperimentRule, error) {
	var body FeatureExperimentRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureExperimentRule overwrites any union data inside the FeatureRule as the provided FeatureExperimentRule
func (t *FeatureRule) FromFeatureExperimentRule(v FeatureExperimentRule) error {
	v.Type = "experiment"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureExperimentRule performs a merge with any union data inside the FeatureRule, using the provided FeatureExperimentRule
func (t *FeatureRule) MergeFeatureExperimentRule(v FeatureExperimentRule) error {
	v.Type = "experiment"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureExperimentRefRule returns the union data inside the FeatureRule as a FeatureExperimentRefRule
func (t FeatureRule) AsFeatureExperimentRefRule() (FeatureExperimentRefRule, error) {
	var body FeatureExperimentRefRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureExperimentRefRule overwrites any union data inside the FeatureRule as the provided FeatureExperimentRefRule
func (t *FeatureRule) FromFeatureExperimentRefRule(v FeatureExperimentRefRule) error {
	v.Type = "experiment-ref"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureExperimentRefRule performs a merge with any union data inside the FeatureRule, using the provided FeatureExperimentRefRule
func (t *FeatureRule) MergeFeatureExperimentRefRule(v FeatureExperimentRefRule) error {
	v.Type = "experiment-ref"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFeatureSafeRolloutRule returns the union data inside the FeatureRule as a FeatureSafeRolloutRule
func (t FeatureRule) AsFeatureSafeRolloutRule() (FeatureSafeRolloutRule, error) {
	var body FeatureSafeRolloutRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFeatureSafeRolloutRule overwrites any union data inside the FeatureRule as the provided FeatureSafeRolloutRule
func (t *FeatureRule) FromFeatureSafeRolloutRule(v FeatureSafeRolloutRule) error {
	v.Type = "safe-rollout"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFeatureSafeRolloutRule performs a merge with any union data inside the FeatureRule, using the provided FeatureSafeRolloutRule
func (t *FeatureRule) MergeFeatureSafeRolloutRule(v FeatureSafeRolloutRule) error {
	v.Type = "safe-rollout"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FeatureRule) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t FeatureRule) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "experiment":
		return t.AsFeatureExperimentRule()
	case "experiment-ref":
		return t.AsFeatureExperimentRefRule()
	case "force":
		return t.AsFeatureForceRule()
	case "rollout":
		return t.AsFeatureRolloutRule()
	case "safe-rollout":
		return t.AsFeatureSafeRolloutRule()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t FeatureRule) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FeatureRule) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListFeatures request
	ListFeatures(ctx context.Context, params *ListFeaturesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListFeatures(ctx context.Context, params *ListFeaturesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListFeaturesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListFeaturesRequest generates requests for ListFeatures
func NewListFeaturesRequest(server string, params *ListFeaturesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/features")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProjectId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "projectId", runtime.ParamLocationQuery, *params.ProjectId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ClientKey != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "clientKey", runtime.ParamLocationQuery, *params.ClientKey); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListFeaturesWithResponse request
	ListFeaturesWithResponse(ctx context.Context, params *ListFeaturesParams, reqEditors ...RequestEditorFn) (*ListFeaturesResponse, error)
}

type ListFeaturesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Count      int       `json:"count"`
		Features   []Feature `json:"features"`
		HasMore    bool      `json:"hasMore"`
		Limit      int       `json:"limit"`
		NextOffset *int      `json:"nextOffset"`
		Offset     int       `json:"offset"`
		Total      int       `json:"total"`
	}
}

// Status returns HTTPResponse.Status
func (r ListFeaturesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListFeaturesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListFeaturesWithResponse request returning *ListFeaturesResponse
func (c *ClientWithResponses) ListFeaturesWithResponse(ctx context.Context, params *ListFeaturesParams, reqEditors ...RequestEditorFn) (*ListFeaturesResponse, error) {
	rsp, err := c.ListFeatures(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListFeaturesResponse(rsp)
}

// ParseListFeaturesResponse parses an HTTP response from a ListFeaturesWithResponse call
func ParseListFeaturesResponse(rsp *http.Response) (*ListFeaturesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListFeaturesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Count      int       `json:"count"`
			Features   []Feature `json:"features"`
			HasMore    bool      `json:"hasMore"`
			Limit      int       `json:"limit"`
			NextOffset *int      `json:"nextOffset"`
			Offset     int       `json:"offset"`
			Total      int       `json:"total"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
