package types

import (
	"context"

	"github.com/growthbook/growthbook-golang"
)

// ArrayFeature is a typed wrapper for a JSON-array GrowthBook feature.
//
// Note: This is a wrapper around the generic Feature type, will not be generated by gbgen.
// GrowthBook's JSON value type can represent any JSON shape; arrays are decoded by
// the Go SDK as []any (with numbers as float64).
type ArrayFeature string

// Key returns the underlying GrowthBook feature key.
func (f ArrayFeature) Key() string {
	return string(f)
}

// Evaluate evaluates the feature using the provided GrowthBook client and optional attributes.
func (f ArrayFeature) Evaluate(ctx context.Context, client *growthbook.Client, attrs ...growthbook.Attributes) (result FeatureResult[[]any], err error) {
	r, err := evaluateWithAttrs(ctx, client, string(f), attrs...)
	if err != nil {
		return result, err
	}

	if _, ok := r.Value.([]any); !ok {
		return result, newTypeMismatchError(string(f), "[]any", r.Value)
	}

	return FeatureResult[[]any]{
		Raw:   r,
		Value: r.Value.([]any),
		Valid: true,
	}, nil
}

// Get evaluates the feature and returns (value, ok) for happy-path usage.
// It never returns an error; any error or type mismatch results in ok=false.
func (f ArrayFeature) Get(ctx context.Context, client *growthbook.Client, attrs ...growthbook.Attributes) (value []any, ok bool) {
	res, err := f.Evaluate(ctx, client, attrs...)
	if err != nil || !res.Valid {
		return nil, false
	}
	return res.Value, true
}

// GetOr evaluates the feature and returns defaultValue if evaluation fails or the value cannot be decoded.
func (f ArrayFeature) GetOr(ctx context.Context, client *growthbook.Client, defaultValue []any, attrs ...growthbook.Attributes) []any {
	if v, ok := f.Get(ctx, client, attrs...); ok {
		return v
	}
	return defaultValue
}
