package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

type preambleOptions struct {
	PackageName  string
	GBGenVersion string
	DocLines     []string
	Imports      []string // import paths
}

func renderPreamble(opts preambleOptions) ([]byte, error) {
	pkg := opts.PackageName
	if pkg == "" {
		pkg = "features"
	}

	var b bytes.Buffer

	// Package doc comment (godoc)
	for _, l := range opts.DocLines {
		l = strings.TrimRight(l, "\n")
		if l == "" {
			fmt.Fprintf(&b, "//\n")
			continue
		}
		fmt.Fprintf(&b, "// %s\n", l)
	}
	if len(opts.DocLines) > 0 {
		fmt.Fprintf(&b, "//\n")
	}

	fmt.Fprintf(&b, "// Code generated by gbgen %s. DO NOT EDIT.\n\n", opts.GBGenVersion)
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	if len(opts.Imports) > 0 {
		imps := append([]string(nil), opts.Imports...)
		sort.Strings(imps)
		fmt.Fprintf(&b, "import (\n")
		for _, imp := range imps {
			fmt.Fprintf(&b, "\t%q\n", imp)
		}
		fmt.Fprintf(&b, ")\n\n")
	}

	// Note: caller appends the rest of the file; we format the whole file later.
	return b.Bytes(), nil
}

func formatGo(src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return src, err
	}
	return out, nil
}
